FROM node:14.0.0 as builder

WORKDIR /cowallet

COPY . .

ENV APP_ENV="prod"
ENV API_BASE="https://proxy.getlinks.jp/"
ENV OAUTH_URL="https://oauth.getlinks.jp/"
ENV CLIENT_ID="5e4af079-5f4a-42e1-a1b7-38081d311cc6"

RUN yarn
RUN yarn generate

FROM nginx:1.12-alpine

COPY --from=builder /cowallet/dist /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
